USER_LIB_PATH := $(realpath ./lib)
ARDUINO_LIBS  := Wire
BOARD_TAG     := uno
ARDUINO_PORT  := /dev/ttyUSB0
CXXFLAGS      += -std=gnu++11 -Wall
CFLAGS        += -std=gnu99 -Wall

include ../../../Arduino-Makefile/Arduino.mk
